steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APPNAME}:COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_APPNAME}:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_APPNAME}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_APPNAME}:$COMMIT_SHA'
  - '--region'
  - 'asia-northeast1'
# Where CB will store the image
images:
- 'gcr.io/$PROJECT_ID/${_APPNAME}:$COMMIT_SHA'
substitutions:
  _APPNAME: "user-api"
