version: '3.7'
services:
  mysqld:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - user_api_network
  
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - 9010:9010
      - 9020:9020
    networks:
      - user_api_network

  redis:
    image: redis
    ports:
      - 6379:6379
      - 6378:6378
    networks:
      - user_api_network

  memcached:
    image: memcached
    ports:
      - 11211:11211
    networks:
      - user_api_network

networks:
  user_api_network:
    name: user_api_network
